FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3004

ENV FLASK_ENV=development
ENV FLASK_APP=app.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=3004"]
